# Generated by Django 6.0.6 on 2026-06-09 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('q1_bed_time', models.TimeField(blank=True, null=True)),
                ('q2_sleep_attempt_time', models.TimeField(blank=True, null=True)),
                ('q3_sleep_latency_min', models.PositiveIntegerField(blank=True, null=True)),
                ('q4_awakening_count', models.PositiveIntegerField(blank=True, null=True)),
                ('q5_waso_min', models.PositiveIntegerField(blank=True, null=True)),
                ('q6a_final_awakening_time', models.TimeField(blank=True, null=True)),
                ('q6b_post_awakening_bed_min', models.PositiveIntegerField(blank=True, null=True)),
                ('q6c_early_awakening', models.BooleanField(blank=True, null=True)),
                ('q6d_early_awakening_min', models.PositiveIntegerField(blank=True, null=True)),
                ('q7_out_of_bed_time', models.TimeField(blank=True, null=True)),
                ('q9_sleep_quality', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Very Good')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q10_restfulness', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Not at all rested'), (2, 'Slightly rested'), (3, 'Somewhat rested'), (4, 'Well-rested'), (5, 'Very well-rested')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q11a_nap_count', models.PositiveIntegerField(blank=True, null=True)),
                ('q11b_nap_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('q12a_alcohol_count', models.PositiveIntegerField(blank=True, null=True)),
                ('q12b_alcohol_last_time', models.TimeField(blank=True, null=True)),
                ('q13a_caffeine_count', models.PositiveIntegerField(blank=True, null=True)),
                ('q13b_caffeine_last_time', models.TimeField(blank=True, null=True)),
                ('q14a_medication_taken', models.BooleanField(blank=True, null=True)),
                ('q14b_medication_details', models.TextField(blank=True, default='')),
                ('q15_comments', models.TextField(blank=True, default='')),
                ('tst_min', models.IntegerField(blank=True, null=True)),
                ('tst_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tib_min', models.IntegerField(blank=True, null=True)),
                ('sleep_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
