# Generated by Django 6.0.6 on 2026-06-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_tz_offset',
            field=models.IntegerField(default=0),
        ),
    ]
