# Generated by Django 6.0.6 on 2026-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_notification_tz_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_notification_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
